apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr-test
  namespace: mediacenter
  labels:
    app: sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sonarr
    spec:
      automountServiceAccountToken: true
      containers:
        - name: sonarr
          image: linuxserver/sonarr:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8989
              name: app-port
              protocol: TCP
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: America/Toronto
            - name: DOCKER_MODS
              value: gilbn/theme.park:sonarr
            - name: TP_THEME
              value: plex
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /sonarr/ping
              port: app-port
