services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    restart: unless-stopped
    networks:
      - mediacenter
    deploy:
      resources:
        limits:
          memory: 24g
    ports:
      - "32400:32400"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PLEX_CLAIM=${PLEX_CLAIM}
    volumes:
      - ${CONFIG_DIR}/plex:/config
      - ${MEDIA_DIR}:/data/media
      - type: tmpfs
        target: /transcode
        tmpfs:
          size: 25769803776 # 24GiB in bytes
    # devices:
    #   - /dev/dri:/dev/dri
    #   - /dev/nvidiactl:/dev/nvidiactl
    #   - /dev/nvidia-modeset:/dev/nvidia-modeset
    #   - /dev/nvidia-uvm:/dev/nvidia-uvm
    #   - /dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools
    #   - /dev/nvidia0:/dev/nvidia0

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    restart: unless-stopped
    networks:
      - mediacenter
    ports:
      - "5055:5055"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_DIR}/overseerr:/config

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    restart: unless-stopped
    networks:
      - mediacenter
    ports:
      - "8181:8181"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_DIR}/tautulli:/config

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    networks:
      - mediacenter
    ports:
      - "8989:8989"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_MODS=gilbn/theme.park:sonarr
      - TP_THEME=plex
    volumes:
      - ${CONFIG_DIR}/sonarr:/config
      - ${TV_SHOWS_DIR}:/data/media/tvshows
      - ${DOWNLOADS_DIR}/sabnzbd:/data/downloads

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    networks:
      - mediacenter
    ports:
      - "7878:7878"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_MODS=gilbn/theme.park:radarr
      - TP_THEME=plex
    volumes:
      - ${CONFIG_DIR}/radarr:/config
      - ${MOVIES_DIR}:/data/media/movies
      - ${DOWNLOADS_DIR}/sabnzbd:/data/downloads

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    networks:
      - mediacenter
    ports:
      - "9696:9696"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_MODS=gilbn/theme.park:prowlarr
      - TP_THEME=plex
    volumes:
      - ${CONFIG_DIR}/prowlarr:/config

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    restart: unless-stopped
    networks:
      - mediacenter
    ports:
      - "8080:8080"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_MODS=gilbn/theme.park:sabnzbd
      - TP_THEME=plex
    volumes:
      - ${CONFIG_DIR}/sabnzbd:/config
      - ${DOWNLOADS_DIR}/sabnzbd:/data/downloads

networks:
  mediacenter:
    driver: bridge
