services:
  cloud-sql-proxy:
    image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.8.2-alpine
    container_name: cloud-sql-proxy
    restart: unless-stopped
    entrypoint: /bin/sh
    command: -c "echo \"$$GOOGLE_APPLICATION_CREDENTIALS_BASE64\" | base64 -d > /credentials.json && /cloud-sql-proxy --address=0.0.0.0 ${CLOUD_SQL_INSTANCES}"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/credentials.json
      - GOOGLE_APPLICATION_CREDENTIALS_BASE64=${CLOUDSQL_BASE64_CREDENTIALS}
    networks:
      - mediacenter
    ports:
      - "30001:3306" # MySQL
      - "30002:5432" # Postgres
