services:
  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${CONFIG_DIR}/homarr:/appdata
    environment:
      - SECRET_ENCRYPTION_KEY=${HOMARR_SECRET_ENCRYPTION_KEY}
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - AUTH_PROVIDERS=credentials,oidc
      - AUTH_OIDC_ISSUER=https://auth.${CLOUDFLARE_ZONE_NAME}/application/o/homarr/
      - AUTH_OIDC_CLIENT_ID=${HOMARR_OIDC_CLIENT_ID}
      - AUTH_OIDC_CLIENT_SECRET=${HOMARR_OIDC_CLIENT_SECRET}
      - AUTH_OIDC_CLIENT_NAME=Plex
      - AUTH_OIDC_SCOPE_OVERWRITE=openid profile email groups
      - AUTH_OIDC_GROUPS_ATTRIBUTE=groups
      - AUTH_OIDC_AUTO_LOGIN=true
      - AUTH_OIDC_ENABLE_DANGEROUS_ACCOUNT_LINKING=true
      - AUTH_LOGOUT_REDIRECT_URL=https://auth.${CLOUDFLARE_ZONE_NAME}/application/o/homarr/end-session/?post_logout_redirect_uri=https://${CLOUDFLARE_ZONE_NAME}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homarr.rule=Host(`${CLOUDFLARE_ZONE_NAME}`)"
      - "traefik.http.routers.homarr.entrypoints=websecure"
      - "traefik.http.services.homarr.loadbalancer.server.port=7575"
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - mediacenter
