services:
  organizr:
    image: organizr/organizr:latest
    container_name: organizr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - branch=v2-master
      - fpm=false
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.organizr.rule=Host(`${CLOUDFLARE_ZONE_NAME}`)"
      - "traefik.http.routers.organizr.entrypoints=websecure"
      - "traefik.http.services.organizr.loadbalancer.server.port=80"
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - mediacenter
    volumes:
      - ${CONFIG_DIR}/organizr:/config
