services:
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - mediacenter
    ports:
      - "5055:5055"
    volumes:
      - ${CONFIG_DIR}/overseerr:/config
      - ./.config/overseerr/settings.json:/config/settings.json
