services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 24g
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PLEX_CLAIM=${PLEX_CLAIM}
    networks:
      - mediacenter
    ports:
      - "32400:32400"
    volumes:
      - ${CONFIG_DIR}/plex:/config
      - ${MEDIA_DIR}:/data/media
      - type: tmpfs
        target: /transcode
        tmpfs:
          size: 25769803776 # 24GiB in bytes
