services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 24g
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PLEX_CLAIM=${PLEX_CLAIM}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plex.rule=Host(`${CLOUDFLARE_ZONE_NAME}`) && PathPrefix(`/web`)"
      - "traefik.http.routers.plex.entrypoints=websecure"
      - "traefik.http.services.plex.loadbalancer.server.port=32400"
    networks:
      - mediacenter
    volumes:
      - ${CONFIG_DIR}/plex:/config
      - ${MEDIA_DIR}:/data/media
      - type: tmpfs
        target: /transcode
        tmpfs:
          size: 25769803776 # 24GiB in bytes
