services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_MODS=gilbn/theme.park:prowlarr
      - TP_THEME=plex
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.${CLOUDFLARE_ZONE_NAME}`)"
      - "traefik.http.routers.prowlarr.entrypoints=websecure"
      - "traefik.http.routers.prowlarr.middlewares=authentik@docker"
      - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - mediacenter
    volumes:
      - ${CONFIG_DIR}/prowlarr:/config
