services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_MODS=gilbn/theme.park:radarr
      - TP_THEME=plex
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=Host(`${CLOUDFLARE_ZONE_NAME}`) && PathPrefix(`/radarr`)"
      - "traefik.http.routers.radarr.entrypoints=websecure"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - mediacenter
    volumes:
      - ${CONFIG_DIR}/radarr:/config
      - ./.config/radarr/config.xml:/config/config.xml
      - ${MOVIES_DIR}:/data/media/movies
      - ${DOWNLOADS_DIR}/sabnzbd:/data/downloads
