services:
  recyclarr:
    image: ghcr.io/recyclarr/recyclarr
    container_name: recyclarr
    restart: unless-stopped
    user: ${PUID}:${PGID}
    environment:
      - TZ=${TZ}
      - RECYCLARR_CREATE_CONFIG=true
    networks:
      - mediacenter
    volumes:
      - ${CONFIG_DIR}/recyclarr:/config
