services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_MODS=gilbn/theme.park:sabnzbd
      - TP_THEME=plex
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sabnzbd.rule=Host(`sabnzbd.${CLOUDFLARE_ZONE_NAME}`)"
      - "traefik.http.routers.sabnzbd.entrypoints=websecure"
      - "traefik.http.routers.sabnzbd.middlewares=authentik@docker"
      - "traefik.http.services.sabnzbd.loadbalancer.server.port=8080"
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - mediacenter
    volumes:
      - ${CONFIG_DIR}/sabnzbd:/config
      - ${DOWNLOADS_DIR}/sabnzbd:/data/downloads
