services:
  scrutiny:
    image: lscr.io/linuxserver/scrutiny:latest
    container_name: scrutiny
    restart: always
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN
    devices:
      - /dev/sda:/dev/sda
      - /dev/sdb:/dev/sdb
      - /dev/sdc:/dev/sdc
      - /dev/sdd:/dev/sdd
      - /dev/sde:/dev/sde
      - /dev/sdf:/dev/sdf
      - /dev/sdg:/dev/sdg
      - /dev/sdh:/dev/sdh
      - /dev/sdi:/dev/sdi
      - /dev/sdj:/dev/sdj
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - SCRUTINY_API_ENDPOINT=http://localhost:8080
      - SCRUTINY_WEB=true
      - SCRUTINY_COLLECTOR=true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.scrutiny.rule=Host(`${CLOUDFLARE_ZONE_NAME}`) && PathPrefix(`/scrutiny`)"
      - "traefik.http.routers.scrutiny.entrypoints=websecure"
      - "traefik.http.services.scrutiny.loadbalancer.server.port=8080"
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - mediacenter
    volumes:
      - ${CONFIG_DIR}/scrutiny:/config
      - /run/udev:/run/udev:ro
