services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_MODS=gilbn/theme.park:sonarr
      - TP_THEME=plex
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.rule=Host(`${CLOUDFLARE_ZONE_NAME}`) && PathPrefix(`/sonarr`)"
      - "traefik.http.routers.sonarr.entrypoints=websecure"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
    networks:
      - mediacenter
    volumes:
      - ${CONFIG_DIR}/sonarr:/config
      - ./.config/sonarr/config.xml:/config/config.xml
      - ${TV_SHOWS_DIR}:/data/media/tvshows
      - ${DOWNLOADS_DIR}/sabnzbd:/data/downloads
