services:
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tautulli.rule=Host(`${CLOUDFLARE_ZONE_NAME}`) && PathPrefix(`/tautulli`)"
      - "traefik.http.routers.tautulli.entrypoints=websecure"
      - "traefik.http.services.tautulli.loadbalancer.server.port=8181"
    networks:
      - mediacenter
    volumes:
      - ${CONFIG_DIR}/tautulli:/config
