services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      - SENDS_ALLOWED=true
      - EMERGENCY_ACCESS_ALLOWED=true
      - DISABLE_ICON_DOWNLOAD=true
      - SIGNUPS_ALLOWED=false
      - ADMIN_TOKEN=${VAULTWARDEN_ADMIN_TOKEN}
      - DISABLE_ADMIN_TOKEN=false
      - INVITATIONS_ALLOWED=false
      - DOMAIN=https://vault.${CLOUDFLARE_ZONE_NAME}
      - SMTP_HOST=${VAULTWARDEN_SMTP_HOST}
      - SMTP_PORT=${VAULTWARDEN_SMTP_PORT}
      - SMTP_FROM_NAME=${VAULTWARDEN_SMTP_FROM_NAME}
      - SMTP_FROM=${VAULTWARDEN_SMTP_USERNAME}
      - SMTP_USERNAME=${VAULTWARDEN_SMTP_USERNAME}
      - SMTP_PASSWORD=${VAULTWARDEN_SMTP_PASSWORD}
      - SMTP_TIMEOUT=${VAULTWARDEN_SMTP_TIMEOUT}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vaultwarden.rule=Host(`vault.${CLOUDFLARE_ZONE_NAME}`)"
      - "traefik.http.routers.vaultwarden.entrypoints=websecure"
      - "traefik.http.services.vaultwarden.loadbalancer.server.port=80"
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - mediacenter
    volumes:
      - ${CONFIG_DIR}/vaultwarden:/data
