services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    environment:
      - WATCHTOWER_LABEL_ENABLE=true
      - DOCKER_API_VERSION=1.44
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - mediacenter
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
