services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    networks:
      - mediacenter
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
